#!/bin/sh

# see Chapter 8 of Debian Linux Kernel Handbook

set -e

# this script is used as postinst.d and postrm.d script; this is used to
# differentiate between the two
self="$0"

# see 8.1, Kernel hooks
abi="$1"
# ignored
_vmlinuz="${2:-/boot/vmlinuz-$abi}"
set -- $DEB_MAINT_PARAMS
action="$1"
action="${action#\'}"
action="${action%\'}"
# ignored
_version="$2"
_version="${version#\'}"
_version="${version%\'}"

# HACK
# For now manually extract the vmlinuz to not have compression
mv ${_vmlinuz} /boot/Image.gz
zcat /boot/Image.gz > ${_vmlinuz}
rm /boot/Image.gz
